---
# The light component allows you to track and control various light bulbs.
# This loads up my light configurations.
#
# https://www.home-assistant.io/integrations/light/
#
media_player: !include_dir_list ../entities/media_player
