---
# Scene: Living Room: Watching a Movie
#
# Used when watching a movie on the TV
#
id: "27369c22-c995-4ec1-9973-1ee538ee4a22"
name: "Watching Movie in Living Room"
icon: mdi:movie-open
entities:
  media_player.living_room_stereo:
    state: on
    volume: 50
    source: tv
  media_player.living_room_tv:
    state: on