---
# Scene: Living Room: Watching a Movie
#
# Used when watching a movie on the TV
#
id: "c3ec8a09-c095-422c-96f2-498ac84e9ac3"
name: "Nothing Playing in Living Room"
icon: mdi:mute
entities:
  media_player.living_room_stereo:
    state: off
  media_player.living_room_tv:
    state: off