---
alias: Lounge Apple TV begins playing
id: "c1ca90e7-e28f-4df8-861f-f60d800fe6e6"
trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
action:
  - service: scene.turn_on
      target:
        entity_id: scene.watching_movie_in_living_room