---
alias: Spotify Connect begins playing
id: "1e1d9ab0-bf98-4ca3-b982-02c3bc36d311"
trigger:
  - platform: state
    entity_id: media_player.living_room_stereo_streamer
    to: 'playing'
action:
  - service: scene.turn_on
    target:
      entity_id: scene.listening_to_music_in_living_room